# Generated by Django 4.1 on 2022-09-04 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='driver_pics')),
                ('active_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LogCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='truck_pics')),
                ('rate', models.FloatField(default=1)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Owners.driver')),
            ],
        ),
        migrations.CreateModel(
            name='OWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(blank=True, max_length=300, null=True)),
                ('public_key', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=0)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Owners.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owners.owner')),
            ],
        ),
    ]
