# Generated by Django 4.1 on 2022-09-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0002_driver_logcache_truck_owallet_container'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OWallet',
            new_name='Wallet',
        ),
    ]
