# Generated by Django 4.1 on 2022-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0003_rename_owallet_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='weight',
            field=models.CharField(default='w', max_length=300),
        ),
    ]
