# Generated by Django 4.1 on 2022-09-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0005_truckdepot_remove_truck_driver_driver_truck_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='TruckDepot',
        ),
    ]
