# Generated by Django 4.1 on 2022-09-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0006_delete_driver_delete_truck_delete_truckdepot'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='weight_range',
            field=models.CharField(default='kg', max_length=300),
        ),
        migrations.AlterField(
            model_name='container',
            name='weight',
            field=models.FloatField(default=200),
        ),
    ]
