# Generated by Django 4.1 on 2022-09-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0007_container_weight_range_alter_container_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='price',
            new_name='price_BTC',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='balance_BTC',
        ),
    ]
