# Generated by Django 4.1 on 2022-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0008_rename_price_container_price_btc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='price_BTC',
            field=models.FloatField(),
        ),
    ]
