# Generated by Django 4.1 on 2022-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0009_alter_container_price_btc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='long',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='***', max_length=300),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(default='***', max_length=300),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(default='***', max_length=300),
        ),
    ]
