# Generated by Django 4.1 on 2022-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0003_truck_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='weight_level',
            field=models.FloatField(default=1),
        ),
    ]
