# Generated by Django 4.1 on 2022-09-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0005_alter_truck_weight_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.CharField(default='me', max_length=300),
        ),
    ]
