# Generated by Django 4.1 on 2022-09-10 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0007_alter_driver_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='driver_pics')),
                ('active_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Drivers.truckdepot')),
            ],
        ),
    ]
