# Generated by Django 4.1 on 2022-09-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers', '0008_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
