# Generated by Django 4.1 on 2022-09-04 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(blank=True, max_length=300, null=True)),
                ('public_key', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('balance', models.FloatField(default=20000)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=200)),
                ('product', models.CharField(default='1', max_length=200)),
                ('product_farmer', models.CharField(default='1', max_length=200)),
                ('farm_location', models.CharField(default='1', max_length=200)),
                ('distance', models.CharField(default='1', max_length=200)),
                ('delivery_type', models.CharField(default='1', max_length=100)),
                ('delivery_fee_ghc', models.FloatField(default=1)),
                ('delivery_duration', models.CharField(default=1, max_length=100)),
                ('amount', models.FloatField(default=1, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
