# Generated by Django 4.1 on 2022-09-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='distance',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='farm_location',
            new_name='container_owner',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='product',
            new_name='depot_location',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='product_farmer',
            new_name='trip_distance',
        ),
    ]
