# Generated by Django 4.1 on 2022-09-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_rename_distance_transactionlog_container_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='shipping_address',
            new_name='pickup',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='driver',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='dropoff',
            field=models.CharField(default='Accra', max_length=200),
        ),
    ]
