# Generated by Django 4.1 on 2022-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_rename_amount_transactionlog_amount_btc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='agent',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='agent_location',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
