# Generated by Django 4.1 on 2022-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_transactionlog_agent_transactionlog_agent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='agent_phone',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='driver_phone',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
