# Generated by Django 4.1 on 2022-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_transactionlog_agent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='amount_GHS',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='amount_BTC',
            field=models.FloatField(default=1),
        ),
    ]
