# Generated by Django 4.1 on 2022-09-12 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_wallet_address_alter_wallet_balance_btc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='duration_stamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
