# Generated by Django 4.1 on 2022-09-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_transactionlog_duration_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='duration_stamp',
            field=models.IntegerField(default=1),
        ),
    ]
