# Generated by Django 4.1 on 2022-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_alter_transactionlog_duration_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin_code',
            field=models.CharField(default='***', max_length=4),
        ),
    ]
