# Generated by Django 4.1 on 2022-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0011_wallet_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pin_code',
            field=models.CharField(default='null', max_length=4),
        ),
    ]
