# Generated by Django 4.1 on 2022-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300, null=True)),
                ('country', models.CharField(default='world', max_length=100, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserLocation',
            new_name='UserDrop',
        ),
    ]
