# Generated by Django 4.1 on 2022-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_userpick_rename_userlocation_userdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickL', models.CharField(max_length=300, null=True)),
                ('pcountry', models.CharField(default='world', max_length=100, null=True)),
                ('plong', models.FloatField(blank=True, null=True)),
                ('plat', models.FloatField(blank=True, null=True)),
                ('dropL', models.CharField(max_length=300, null=True)),
                ('dcountry', models.CharField(default='world', max_length=100, null=True)),
                ('dlong', models.FloatField(blank=True, null=True)),
                ('dlat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDrop',
        ),
        migrations.DeleteModel(
            name='UserPick',
        ),
    ]
